# Node.js Express Web App to Linux on Azure
# Build a Node.js Express app and deploy it to Azure as a Linux web app.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

variables:

  # Azure Resource Manager connection created during pipeline creation
  azureSubscription: 'c8aed0d9-3ff2-439e-aecb-cf9ce4698ed6'

  # Web app name
  webAppName: 'FirstExpressApp777'

  # Environment name
  environmentName: 'FirstExpressApp777'

  # Agent VM image name
  vmImageName: 'ubuntu-latest'

stages:
- stage: Build
  displayName: Build stage
  jobs:
  - job: BuildJob
    steps:
    - script: npm install
      displayName: 'Install Dependencies'
      workingDirectory: $(System.DefaultWorkingDirectory)
        
    - script: npm run build
      displayName: 'Build Node.js App'
      workingDirectory: $(System.DefaultWorkingDirectory)
        
    - task: CopyFiles@2
      displayName: 'Copy Files to Artifact Staging'
      inputs:
        SourceFolder: $(System.DefaultWorkingDirectory)
        Contents: '**'
        TargetFolder: $(Build.ArtifactStagingDirectory)
          
    - task: PublishPipelineArtifact@1
      displayName: 'Publish Artifact'
      inputs:
        artifactName: 'drop'
        targetPath: $(Build.ArtifactStagingDirectory)


- stage: Deploy
  displayName: Deploy stage
  dependsOn: Build
  condition: succeeded()
  jobs:
  - deployment: DeployJob
    environment: 'production'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: DownloadPipelineArtifact@2
            displayName: 'Download Artifact'
            inputs:
              artifactName: 'drop'
              targetPath: $(System.DefaultWorkingDirectory)
                
          - script: npm install && npm run start
            displayName: 'Install Dependencies'
            workingDirectory: $(System.DefaultWorkingDirectory)
              
          - task: AzureRmWebAppDeployment@4
            displayName: 'Azure App Service Deploy'
            inputs:
              ConnectionType: 'AzureRM'
              azureSubscription: '<AzureSubscriptionName>'
              appType: 'webAppLinux'
              WebAppName: '<AppServiceName>'
              packageForLinux: '$(System.DefaultWorkingDirectory)/**/*.zip'
