trigger:
- main

# Use a single pool/job to ensure everything runs in sequence on one agent
pool:
  name: 'SelfHostedAgent1'

variables:
  # Azure Resource Manager service connection name
  azureSubscription: 'NewAzureRMConnection'

  # Web app name
  webAppName: 'FirstExpressApp777'

steps:
- script: |
    echo "Installing dependencies (development)"
    npm install
  displayName: 'Install Dependencies (Dev)'

- script: |
    echo "Building Node.js App"
    npm run build
  displayName: 'Build Node.js App'

- task: ArchiveFiles@2
  displayName: 'Archive Files'
  inputs:
    rootFolderOrFile: '$(System.DefaultWorkingDirectory)'
    includeRootFolder: false
    archiveType: zip
    archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    replaceExistingArchive: true

- script: |
    echo "Installing dependencies (production)"
    npm install --production
  displayName: 'Install Dependencies (Prod)'

- task: AzureRmWebAppDeployment@4
  displayName: 'Azure App Service Deploy'
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: '$(azureSubscription)'
    appType: 'webAppLinux'
    WebAppName: '$(webAppName)'
    packageForLinux: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
